/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchesRouteImport } from './routes/watches'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as BriefBriefIdIndexRouteImport } from './routes/brief.$briefId.index'
import { Route as BriefBriefIdWatchRouteImport } from './routes/brief.$briefId.watch'
import { Route as BriefBriefIdSignalSignalIdRouteImport } from './routes/brief.$briefId.signal.$signalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesRoute = WatchesRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefBriefIdIndexRoute = BriefBriefIdIndexRouteImport.update({
  id: '/brief/$briefId/',
  path: '/brief/$briefId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefBriefIdWatchRoute = BriefBriefIdWatchRouteImport.update({
  id: '/brief/$briefId/watch',
  path: '/brief/$briefId/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefBriefIdSignalSignalIdRoute =
  BriefBriefIdSignalSignalIdRouteImport.update({
    id: '/brief/$briefId/signal/$signalId',
    path: '/brief/$briefId/signal/$signalId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watches': typeof WatchesRoute
  '/share/$token': typeof ShareTokenRoute
  '/brief/$briefId/watch': typeof BriefBriefIdWatchRoute
  '/brief/$briefId/': typeof BriefBriefIdIndexRoute
  '/brief/$briefId/signal/$signalId': typeof BriefBriefIdSignalSignalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watches': typeof WatchesRoute
  '/share/$token': typeof ShareTokenRoute
  '/brief/$briefId/watch': typeof BriefBriefIdWatchRoute
  '/brief/$briefId': typeof BriefBriefIdIndexRoute
  '/brief/$briefId/signal/$signalId': typeof BriefBriefIdSignalSignalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watches': typeof WatchesRoute
  '/share/$token': typeof ShareTokenRoute
  '/brief/$briefId/watch': typeof BriefBriefIdWatchRoute
  '/brief/$briefId/': typeof BriefBriefIdIndexRoute
  '/brief/$briefId/signal/$signalId': typeof BriefBriefIdSignalSignalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/watches'
    | '/share/$token'
    | '/brief/$briefId/watch'
    | '/brief/$briefId/'
    | '/brief/$briefId/signal/$signalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/watches'
    | '/share/$token'
    | '/brief/$briefId/watch'
    | '/brief/$briefId'
    | '/brief/$briefId/signal/$signalId'
  id:
    | '__root__'
    | '/'
    | '/watches'
    | '/share/$token'
    | '/brief/$briefId/watch'
    | '/brief/$briefId/'
    | '/brief/$briefId/signal/$signalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchesRoute: typeof WatchesRoute
  ShareTokenRoute: typeof ShareTokenRoute
  BriefBriefIdWatchRoute: typeof BriefBriefIdWatchRoute
  BriefBriefIdIndexRoute: typeof BriefBriefIdIndexRoute
  BriefBriefIdSignalSignalIdRoute: typeof BriefBriefIdSignalSignalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches': {
      id: '/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof WatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$briefId/': {
      id: '/brief/$briefId/'
      path: '/brief/$briefId'
      fullPath: '/brief/$briefId/'
      preLoaderRoute: typeof BriefBriefIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$briefId/watch': {
      id: '/brief/$briefId/watch'
      path: '/brief/$briefId/watch'
      fullPath: '/brief/$briefId/watch'
      preLoaderRoute: typeof BriefBriefIdWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$briefId/signal/$signalId': {
      id: '/brief/$briefId/signal/$signalId'
      path: '/brief/$briefId/signal/$signalId'
      fullPath: '/brief/$briefId/signal/$signalId'
      preLoaderRoute: typeof BriefBriefIdSignalSignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchesRoute: WatchesRoute,
  ShareTokenRoute: ShareTokenRoute,
  BriefBriefIdWatchRoute: BriefBriefIdWatchRoute,
  BriefBriefIdIndexRoute: BriefBriefIdIndexRoute,
  BriefBriefIdSignalSignalIdRoute: BriefBriefIdSignalSignalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
