/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedHowItWorksRouteImport } from './routes/_authenticated/how-it-works'
import { Route as AuthenticatedKnownFlightRouteImport } from './routes/_authenticated/known-flight'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedYouRouteImport } from './routes/_authenticated/you'
import { Route as AuthenticatedEscapeIndexRouteImport } from './routes/_authenticated/escape.index'
import { Route as AuthenticatedPlanIndexRouteImport } from './routes/_authenticated/plan.index'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans.index'
import { Route as AuthenticatedUpdatesIndexRouteImport } from './routes/_authenticated/updates.index'
import { Route as AuthenticatedUpdatesWatchIdRouteImport } from './routes/_authenticated/updates.$watchId'
import { Route as AuthenticatedWatchingIndexRouteImport } from './routes/_authenticated/watching.index'
import { Route as AuthenticatedWatchingWatchIdRouteImport } from './routes/_authenticated/watching.$watchId'
import { Route as ApiPublicRunWatchesRouteImport } from './routes/api/public/run-watches'
import { Route as AuthenticatedEscapePlanIdIndexRouteImport } from './routes/_authenticated/escape.$planId.index'
import { Route as AuthenticatedOptionsOptionIdIndexRouteImport } from './routes/_authenticated/options.$optionId.index'
import { Route as AuthenticatedOptionsOptionIdAvailabilityRouteImport } from './routes/_authenticated/options.$optionId.availability'
import { Route as AuthenticatedOptionsOptionIdLoadRouteImport } from './routes/_authenticated/options.$optionId.load'
import { Route as AuthenticatedOptionsOptionIdRecoveryRouteImport } from './routes/_authenticated/options.$optionId.recovery'
import { Route as AuthenticatedPlansPlanIdIndexRouteImport } from './routes/_authenticated/plans.$planId.index'
import { Route as AuthenticatedPlansPlanIdCompareRouteImport } from './routes/_authenticated/plans.$planId.compare'
import { Route as AuthenticatedPlansPlanIdLoadsRouteImport } from './routes/_authenticated/plans.$planId.loads'
import { Route as AuthenticatedPlansPlanIdOptionsRouteImport } from './routes/_authenticated/plans.$planId.options'
import { Route as AuthenticatedPlansPlanIdWaysRouteImport } from './routes/_authenticated/plans.$planId.ways'
import { Route as AuthenticatedEscapePlanIdViaHubRouteImport } from './routes/_authenticated/escape.$planId.via.$hub'
import { Route as AuthenticatedOptionsOptionIdContextHistoryRouteImport } from './routes/_authenticated/options.$optionId.context.history'
import { Route as AuthenticatedOptionsOptionIdContextHolidayRouteImport } from './routes/_authenticated/options.$optionId.context.holiday'
import { Route as AuthenticatedOptionsOptionIdContextWeatherRouteImport } from './routes/_authenticated/options.$optionId.context.weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHowItWorksRoute = AuthenticatedHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnownFlightRoute =
  AuthenticatedKnownFlightRouteImport.update({
    id: '/known-flight',
    path: '/known-flight',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYouRoute = AuthenticatedYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscapeIndexRoute =
  AuthenticatedEscapeIndexRouteImport.update({
    id: '/escape/',
    path: '/escape/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanIndexRoute = AuthenticatedPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpdatesIndexRoute =
  AuthenticatedUpdatesIndexRouteImport.update({
    id: '/updates/',
    path: '/updates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUpdatesWatchIdRoute =
  AuthenticatedUpdatesWatchIdRouteImport.update({
    id: '/updates/$watchId',
    path: '/updates/$watchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWatchingIndexRoute =
  AuthenticatedWatchingIndexRouteImport.update({
    id: '/watching/',
    path: '/watching/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWatchingWatchIdRoute =
  AuthenticatedWatchingWatchIdRouteImport.update({
    id: '/watching/$watchId',
    path: '/watching/$watchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRunWatchesRoute = ApiPublicRunWatchesRouteImport.update({
  id: '/api/public/run-watches',
  path: '/api/public/run-watches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEscapePlanIdIndexRoute =
  AuthenticatedEscapePlanIdIndexRouteImport.update({
    id: '/escape/$planId/',
    path: '/escape/$planId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptionsOptionIdIndexRoute =
  AuthenticatedOptionsOptionIdIndexRouteImport.update({
    id: '/options/$optionId/',
    path: '/options/$optionId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptionsOptionIdAvailabilityRoute =
  AuthenticatedOptionsOptionIdAvailabilityRouteImport.update({
    id: '/options/$optionId/availability',
    path: '/options/$optionId/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptionsOptionIdLoadRoute =
  AuthenticatedOptionsOptionIdLoadRouteImport.update({
    id: '/options/$optionId/load',
    path: '/options/$optionId/load',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptionsOptionIdRecoveryRoute =
  AuthenticatedOptionsOptionIdRecoveryRouteImport.update({
    id: '/options/$optionId/recovery',
    path: '/options/$optionId/recovery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlanIdIndexRoute =
  AuthenticatedPlansPlanIdIndexRouteImport.update({
    id: '/plans/$planId/',
    path: '/plans/$planId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlanIdCompareRoute =
  AuthenticatedPlansPlanIdCompareRouteImport.update({
    id: '/plans/$planId/compare',
    path: '/plans/$planId/compare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlanIdLoadsRoute =
  AuthenticatedPlansPlanIdLoadsRouteImport.update({
    id: '/plans/$planId/loads',
    path: '/plans/$planId/loads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlanIdOptionsRoute =
  AuthenticatedPlansPlanIdOptionsRouteImport.update({
    id: '/plans/$planId/options',
    path: '/plans/$planId/options',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlanIdWaysRoute =
  AuthenticatedPlansPlanIdWaysRouteImport.update({
    id: '/plans/$planId/ways',
    path: '/plans/$planId/ways',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscapePlanIdViaHubRoute =
  AuthenticatedEscapePlanIdViaHubRouteImport.update({
    id: '/escape/$planId/via/$hub',
    path: '/escape/$planId/via/$hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptionsOptionIdContextHistoryRoute =
  AuthenticatedOptionsOptionIdContextHistoryRouteImport.update({
    id: '/options/$optionId/context/history',
    path: '/options/$optionId/context/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptionsOptionIdContextHolidayRoute =
  AuthenticatedOptionsOptionIdContextHolidayRouteImport.update({
    id: '/options/$optionId/context/holiday',
    path: '/options/$optionId/context/holiday',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptionsOptionIdContextWeatherRoute =
  AuthenticatedOptionsOptionIdContextWeatherRouteImport.update({
    id: '/options/$optionId/context/weather',
    path: '/options/$optionId/context/weather',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/known-flight': typeof AuthenticatedKnownFlightRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/you': typeof AuthenticatedYouRoute
  '/updates/$watchId': typeof AuthenticatedUpdatesWatchIdRoute
  '/watching/$watchId': typeof AuthenticatedWatchingWatchIdRoute
  '/api/public/run-watches': typeof ApiPublicRunWatchesRoute
  '/escape/': typeof AuthenticatedEscapeIndexRoute
  '/plan/': typeof AuthenticatedPlanIndexRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
  '/updates/': typeof AuthenticatedUpdatesIndexRoute
  '/watching/': typeof AuthenticatedWatchingIndexRoute
  '/options/$optionId/availability': typeof AuthenticatedOptionsOptionIdAvailabilityRoute
  '/options/$optionId/load': typeof AuthenticatedOptionsOptionIdLoadRoute
  '/options/$optionId/recovery': typeof AuthenticatedOptionsOptionIdRecoveryRoute
  '/plans/$planId/compare': typeof AuthenticatedPlansPlanIdCompareRoute
  '/plans/$planId/loads': typeof AuthenticatedPlansPlanIdLoadsRoute
  '/plans/$planId/options': typeof AuthenticatedPlansPlanIdOptionsRoute
  '/plans/$planId/ways': typeof AuthenticatedPlansPlanIdWaysRoute
  '/escape/$planId/': typeof AuthenticatedEscapePlanIdIndexRoute
  '/options/$optionId/': typeof AuthenticatedOptionsOptionIdIndexRoute
  '/plans/$planId/': typeof AuthenticatedPlansPlanIdIndexRoute
  '/escape/$planId/via/$hub': typeof AuthenticatedEscapePlanIdViaHubRoute
  '/options/$optionId/context/history': typeof AuthenticatedOptionsOptionIdContextHistoryRoute
  '/options/$optionId/context/holiday': typeof AuthenticatedOptionsOptionIdContextHolidayRoute
  '/options/$optionId/context/weather': typeof AuthenticatedOptionsOptionIdContextWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/known-flight': typeof AuthenticatedKnownFlightRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/you': typeof AuthenticatedYouRoute
  '/updates/$watchId': typeof AuthenticatedUpdatesWatchIdRoute
  '/watching/$watchId': typeof AuthenticatedWatchingWatchIdRoute
  '/api/public/run-watches': typeof ApiPublicRunWatchesRoute
  '/escape': typeof AuthenticatedEscapeIndexRoute
  '/plan': typeof AuthenticatedPlanIndexRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
  '/updates': typeof AuthenticatedUpdatesIndexRoute
  '/watching': typeof AuthenticatedWatchingIndexRoute
  '/options/$optionId/availability': typeof AuthenticatedOptionsOptionIdAvailabilityRoute
  '/options/$optionId/load': typeof AuthenticatedOptionsOptionIdLoadRoute
  '/options/$optionId/recovery': typeof AuthenticatedOptionsOptionIdRecoveryRoute
  '/plans/$planId/compare': typeof AuthenticatedPlansPlanIdCompareRoute
  '/plans/$planId/loads': typeof AuthenticatedPlansPlanIdLoadsRoute
  '/plans/$planId/options': typeof AuthenticatedPlansPlanIdOptionsRoute
  '/plans/$planId/ways': typeof AuthenticatedPlansPlanIdWaysRoute
  '/escape/$planId': typeof AuthenticatedEscapePlanIdIndexRoute
  '/options/$optionId': typeof AuthenticatedOptionsOptionIdIndexRoute
  '/plans/$planId': typeof AuthenticatedPlansPlanIdIndexRoute
  '/escape/$planId/via/$hub': typeof AuthenticatedEscapePlanIdViaHubRoute
  '/options/$optionId/context/history': typeof AuthenticatedOptionsOptionIdContextHistoryRoute
  '/options/$optionId/context/holiday': typeof AuthenticatedOptionsOptionIdContextHolidayRoute
  '/options/$optionId/context/weather': typeof AuthenticatedOptionsOptionIdContextWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/_authenticated/known-flight': typeof AuthenticatedKnownFlightRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/you': typeof AuthenticatedYouRoute
  '/_authenticated/updates/$watchId': typeof AuthenticatedUpdatesWatchIdRoute
  '/_authenticated/watching/$watchId': typeof AuthenticatedWatchingWatchIdRoute
  '/api/public/run-watches': typeof ApiPublicRunWatchesRoute
  '/_authenticated/escape/': typeof AuthenticatedEscapeIndexRoute
  '/_authenticated/plan/': typeof AuthenticatedPlanIndexRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/_authenticated/updates/': typeof AuthenticatedUpdatesIndexRoute
  '/_authenticated/watching/': typeof AuthenticatedWatchingIndexRoute
  '/_authenticated/options/$optionId/availability': typeof AuthenticatedOptionsOptionIdAvailabilityRoute
  '/_authenticated/options/$optionId/load': typeof AuthenticatedOptionsOptionIdLoadRoute
  '/_authenticated/options/$optionId/recovery': typeof AuthenticatedOptionsOptionIdRecoveryRoute
  '/_authenticated/plans/$planId/compare': typeof AuthenticatedPlansPlanIdCompareRoute
  '/_authenticated/plans/$planId/loads': typeof AuthenticatedPlansPlanIdLoadsRoute
  '/_authenticated/plans/$planId/options': typeof AuthenticatedPlansPlanIdOptionsRoute
  '/_authenticated/plans/$planId/ways': typeof AuthenticatedPlansPlanIdWaysRoute
  '/_authenticated/escape/$planId/': typeof AuthenticatedEscapePlanIdIndexRoute
  '/_authenticated/options/$optionId/': typeof AuthenticatedOptionsOptionIdIndexRoute
  '/_authenticated/plans/$planId/': typeof AuthenticatedPlansPlanIdIndexRoute
  '/_authenticated/escape/$planId/via/$hub': typeof AuthenticatedEscapePlanIdViaHubRoute
  '/_authenticated/options/$optionId/context/history': typeof AuthenticatedOptionsOptionIdContextHistoryRoute
  '/_authenticated/options/$optionId/context/holiday': typeof AuthenticatedOptionsOptionIdContextHolidayRoute
  '/_authenticated/options/$optionId/context/weather': typeof AuthenticatedOptionsOptionIdContextWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/how-it-works'
    | '/known-flight'
    | '/welcome'
    | '/you'
    | '/updates/$watchId'
    | '/watching/$watchId'
    | '/api/public/run-watches'
    | '/escape/'
    | '/plan/'
    | '/plans/'
    | '/updates/'
    | '/watching/'
    | '/options/$optionId/availability'
    | '/options/$optionId/load'
    | '/options/$optionId/recovery'
    | '/plans/$planId/compare'
    | '/plans/$planId/loads'
    | '/plans/$planId/options'
    | '/plans/$planId/ways'
    | '/escape/$planId/'
    | '/options/$optionId/'
    | '/plans/$planId/'
    | '/escape/$planId/via/$hub'
    | '/options/$optionId/context/history'
    | '/options/$optionId/context/holiday'
    | '/options/$optionId/context/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/how-it-works'
    | '/known-flight'
    | '/welcome'
    | '/you'
    | '/updates/$watchId'
    | '/watching/$watchId'
    | '/api/public/run-watches'
    | '/escape'
    | '/plan'
    | '/plans'
    | '/updates'
    | '/watching'
    | '/options/$optionId/availability'
    | '/options/$optionId/load'
    | '/options/$optionId/recovery'
    | '/plans/$planId/compare'
    | '/plans/$planId/loads'
    | '/plans/$planId/options'
    | '/plans/$planId/ways'
    | '/escape/$planId'
    | '/options/$optionId'
    | '/plans/$planId'
    | '/escape/$planId/via/$hub'
    | '/options/$optionId/context/history'
    | '/options/$optionId/context/holiday'
    | '/options/$optionId/context/weather'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/how-it-works'
    | '/_authenticated/known-flight'
    | '/_authenticated/welcome'
    | '/_authenticated/you'
    | '/_authenticated/updates/$watchId'
    | '/_authenticated/watching/$watchId'
    | '/api/public/run-watches'
    | '/_authenticated/escape/'
    | '/_authenticated/plan/'
    | '/_authenticated/plans/'
    | '/_authenticated/updates/'
    | '/_authenticated/watching/'
    | '/_authenticated/options/$optionId/availability'
    | '/_authenticated/options/$optionId/load'
    | '/_authenticated/options/$optionId/recovery'
    | '/_authenticated/plans/$planId/compare'
    | '/_authenticated/plans/$planId/loads'
    | '/_authenticated/plans/$planId/options'
    | '/_authenticated/plans/$planId/ways'
    | '/_authenticated/escape/$planId/'
    | '/_authenticated/options/$optionId/'
    | '/_authenticated/plans/$planId/'
    | '/_authenticated/escape/$planId/via/$hub'
    | '/_authenticated/options/$optionId/context/history'
    | '/_authenticated/options/$optionId/context/holiday'
    | '/_authenticated/options/$optionId/context/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiPublicRunWatchesRoute: typeof ApiPublicRunWatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/how-it-works': {
      id: '/_authenticated/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AuthenticatedHowItWorksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/known-flight': {
      id: '/_authenticated/known-flight'
      path: '/known-flight'
      fullPath: '/known-flight'
      preLoaderRoute: typeof AuthenticatedKnownFlightRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/you': {
      id: '/_authenticated/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof AuthenticatedYouRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escape/': {
      id: '/_authenticated/escape/'
      path: '/escape'
      fullPath: '/escape/'
      preLoaderRoute: typeof AuthenticatedEscapeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan/': {
      id: '/_authenticated/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthenticatedPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates/': {
      id: '/_authenticated/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof AuthenticatedUpdatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates/$watchId': {
      id: '/_authenticated/updates/$watchId'
      path: '/updates/$watchId'
      fullPath: '/updates/$watchId'
      preLoaderRoute: typeof AuthenticatedUpdatesWatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watching/': {
      id: '/_authenticated/watching/'
      path: '/watching'
      fullPath: '/watching/'
      preLoaderRoute: typeof AuthenticatedWatchingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watching/$watchId': {
      id: '/_authenticated/watching/$watchId'
      path: '/watching/$watchId'
      fullPath: '/watching/$watchId'
      preLoaderRoute: typeof AuthenticatedWatchingWatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/run-watches': {
      id: '/api/public/run-watches'
      path: '/api/public/run-watches'
      fullPath: '/api/public/run-watches'
      preLoaderRoute: typeof ApiPublicRunWatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/escape/$planId/': {
      id: '/_authenticated/escape/$planId/'
      path: '/escape/$planId'
      fullPath: '/escape/$planId/'
      preLoaderRoute: typeof AuthenticatedEscapePlanIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/options/$optionId/': {
      id: '/_authenticated/options/$optionId/'
      path: '/options/$optionId'
      fullPath: '/options/$optionId/'
      preLoaderRoute: typeof AuthenticatedOptionsOptionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/options/$optionId/availability': {
      id: '/_authenticated/options/$optionId/availability'
      path: '/options/$optionId/availability'
      fullPath: '/options/$optionId/availability'
      preLoaderRoute: typeof AuthenticatedOptionsOptionIdAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/options/$optionId/load': {
      id: '/_authenticated/options/$optionId/load'
      path: '/options/$optionId/load'
      fullPath: '/options/$optionId/load'
      preLoaderRoute: typeof AuthenticatedOptionsOptionIdLoadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/options/$optionId/recovery': {
      id: '/_authenticated/options/$optionId/recovery'
      path: '/options/$optionId/recovery'
      fullPath: '/options/$optionId/recovery'
      preLoaderRoute: typeof AuthenticatedOptionsOptionIdRecoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$planId/': {
      id: '/_authenticated/plans/$planId/'
      path: '/plans/$planId'
      fullPath: '/plans/$planId/'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$planId/compare': {
      id: '/_authenticated/plans/$planId/compare'
      path: '/plans/$planId/compare'
      fullPath: '/plans/$planId/compare'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdCompareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$planId/loads': {
      id: '/_authenticated/plans/$planId/loads'
      path: '/plans/$planId/loads'
      fullPath: '/plans/$planId/loads'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdLoadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$planId/options': {
      id: '/_authenticated/plans/$planId/options'
      path: '/plans/$planId/options'
      fullPath: '/plans/$planId/options'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdOptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/$planId/ways': {
      id: '/_authenticated/plans/$planId/ways'
      path: '/plans/$planId/ways'
      fullPath: '/plans/$planId/ways'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdWaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escape/$planId/via/$hub': {
      id: '/_authenticated/escape/$planId/via/$hub'
      path: '/escape/$planId/via/$hub'
      fullPath: '/escape/$planId/via/$hub'
      preLoaderRoute: typeof AuthenticatedEscapePlanIdViaHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/options/$optionId/context/history': {
      id: '/_authenticated/options/$optionId/context/history'
      path: '/options/$optionId/context/history'
      fullPath: '/options/$optionId/context/history'
      preLoaderRoute: typeof AuthenticatedOptionsOptionIdContextHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/options/$optionId/context/holiday': {
      id: '/_authenticated/options/$optionId/context/holiday'
      path: '/options/$optionId/context/holiday'
      fullPath: '/options/$optionId/context/holiday'
      preLoaderRoute: typeof AuthenticatedOptionsOptionIdContextHolidayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/options/$optionId/context/weather': {
      id: '/_authenticated/options/$optionId/context/weather'
      path: '/options/$optionId/context/weather'
      fullPath: '/options/$optionId/context/weather'
      preLoaderRoute: typeof AuthenticatedOptionsOptionIdContextWeatherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHowItWorksRoute: typeof AuthenticatedHowItWorksRoute
  AuthenticatedKnownFlightRoute: typeof AuthenticatedKnownFlightRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedYouRoute: typeof AuthenticatedYouRoute
  AuthenticatedUpdatesWatchIdRoute: typeof AuthenticatedUpdatesWatchIdRoute
  AuthenticatedWatchingWatchIdRoute: typeof AuthenticatedWatchingWatchIdRoute
  AuthenticatedEscapeIndexRoute: typeof AuthenticatedEscapeIndexRoute
  AuthenticatedPlanIndexRoute: typeof AuthenticatedPlanIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedUpdatesIndexRoute: typeof AuthenticatedUpdatesIndexRoute
  AuthenticatedWatchingIndexRoute: typeof AuthenticatedWatchingIndexRoute
  AuthenticatedOptionsOptionIdAvailabilityRoute: typeof AuthenticatedOptionsOptionIdAvailabilityRoute
  AuthenticatedOptionsOptionIdLoadRoute: typeof AuthenticatedOptionsOptionIdLoadRoute
  AuthenticatedOptionsOptionIdRecoveryRoute: typeof AuthenticatedOptionsOptionIdRecoveryRoute
  AuthenticatedPlansPlanIdCompareRoute: typeof AuthenticatedPlansPlanIdCompareRoute
  AuthenticatedPlansPlanIdLoadsRoute: typeof AuthenticatedPlansPlanIdLoadsRoute
  AuthenticatedPlansPlanIdOptionsRoute: typeof AuthenticatedPlansPlanIdOptionsRoute
  AuthenticatedPlansPlanIdWaysRoute: typeof AuthenticatedPlansPlanIdWaysRoute
  AuthenticatedEscapePlanIdIndexRoute: typeof AuthenticatedEscapePlanIdIndexRoute
  AuthenticatedOptionsOptionIdIndexRoute: typeof AuthenticatedOptionsOptionIdIndexRoute
  AuthenticatedPlansPlanIdIndexRoute: typeof AuthenticatedPlansPlanIdIndexRoute
  AuthenticatedEscapePlanIdViaHubRoute: typeof AuthenticatedEscapePlanIdViaHubRoute
  AuthenticatedOptionsOptionIdContextHistoryRoute: typeof AuthenticatedOptionsOptionIdContextHistoryRoute
  AuthenticatedOptionsOptionIdContextHolidayRoute: typeof AuthenticatedOptionsOptionIdContextHolidayRoute
  AuthenticatedOptionsOptionIdContextWeatherRoute: typeof AuthenticatedOptionsOptionIdContextWeatherRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHowItWorksRoute: AuthenticatedHowItWorksRoute,
  AuthenticatedKnownFlightRoute: AuthenticatedKnownFlightRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedYouRoute: AuthenticatedYouRoute,
  AuthenticatedUpdatesWatchIdRoute: AuthenticatedUpdatesWatchIdRoute,
  AuthenticatedWatchingWatchIdRoute: AuthenticatedWatchingWatchIdRoute,
  AuthenticatedEscapeIndexRoute: AuthenticatedEscapeIndexRoute,
  AuthenticatedPlanIndexRoute: AuthenticatedPlanIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedUpdatesIndexRoute: AuthenticatedUpdatesIndexRoute,
  AuthenticatedWatchingIndexRoute: AuthenticatedWatchingIndexRoute,
  AuthenticatedOptionsOptionIdAvailabilityRoute:
    AuthenticatedOptionsOptionIdAvailabilityRoute,
  AuthenticatedOptionsOptionIdLoadRoute: AuthenticatedOptionsOptionIdLoadRoute,
  AuthenticatedOptionsOptionIdRecoveryRoute:
    AuthenticatedOptionsOptionIdRecoveryRoute,
  AuthenticatedPlansPlanIdCompareRoute: AuthenticatedPlansPlanIdCompareRoute,
  AuthenticatedPlansPlanIdLoadsRoute: AuthenticatedPlansPlanIdLoadsRoute,
  AuthenticatedPlansPlanIdOptionsRoute: AuthenticatedPlansPlanIdOptionsRoute,
  AuthenticatedPlansPlanIdWaysRoute: AuthenticatedPlansPlanIdWaysRoute,
  AuthenticatedEscapePlanIdIndexRoute: AuthenticatedEscapePlanIdIndexRoute,
  AuthenticatedOptionsOptionIdIndexRoute:
    AuthenticatedOptionsOptionIdIndexRoute,
  AuthenticatedPlansPlanIdIndexRoute: AuthenticatedPlansPlanIdIndexRoute,
  AuthenticatedEscapePlanIdViaHubRoute: AuthenticatedEscapePlanIdViaHubRoute,
  AuthenticatedOptionsOptionIdContextHistoryRoute:
    AuthenticatedOptionsOptionIdContextHistoryRoute,
  AuthenticatedOptionsOptionIdContextHolidayRoute:
    AuthenticatedOptionsOptionIdContextHolidayRoute,
  AuthenticatedOptionsOptionIdContextWeatherRoute:
    AuthenticatedOptionsOptionIdContextWeatherRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ApiPublicRunWatchesRoute: ApiPublicRunWatchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
